added accordions, blockquotes, and new sandboxes
learlab/strapi pull request #21
Opened 2024-07-27 02:45 UTC by theannachen

2024-07-27 20:10 UTC, langdonholmes requested changes
Hi Anna,

I noticed that linebreaks are not respected by `.textcontent` or by the turndown service's `content` argument. Basically, HTML is currently converted as follows:
```html
    <p>
        But now lline breaks<br>
        Double linebreaks<br>
    </p>
```

```
<Info title="asdf">
But now lline breaksDouble linebreaks
</Info>
```

We should probably be using the `node` parameter and accessing it's `.innerHTML`. But that will include text formatting and whatever other HTML tags are allowed within a given element, so I'm not sure exactly how to implement this. Can you look into making this change? This can be a separate PR.

Other stuff we have already discussed:

1. I'd like to see a better UX for the accordions. This is the main blocking issue.
2. Please change "Coding Sandbox" to "REPL" in the UI.

A general note is to please add comments and keep comments updated when you change things. If you change code such that a comment no longer makes sense, that comment needs to be updated or removed. One example of this is the "InfoRule" in the mdx parser, which should be named "AccordionRule" (and its comments should be updated).

Lastly, I have a few clarifying questions:

1. Why are we adding/deleting linebreaks in several places? I couldn't follow the logic or motivation here. Replacing all double linebreaks with a single linebreak seems like it could be frustrating for content authors -- we would like the MDX to reflect the CKEditor View as closely as possible.
2. What happened to the dollar sign escaping? I remember we were having issues with the MDX containing unescaped `$`. Is this no longer an issue? Why not? If so, let's just delete that code. It will be in the git history forever if we need it again.

2024-07-28 02:18 UTC, theannachen commented on src/plugins/auto-content/server/services/mdx-service.js
> +    content = content.trim().replace("\n\n","\n")
Since we added the other info, callout, etc, this is only used for the new blockquote feature, where the newlines are being parsed as double.

2024-07-31 15:11 UTC, langdonholmes requested changes
Hi Anna,

This looks good, but I'm still confused by your response about `content.trim().replace("\n\n","\n")` in the "styles" rule.

This rule appears to apply to several elements, but it looks like it is only meant for blockquotes. Could you explain this further and/or clarify what is happening in the code and why it is necessary? If the problem is indeed 'newlines being parsed as double', then it seems like the solution should be to prevent that from happening, rather than deleting the extra newlines after the fact.

2024-07-31 15:11 UTC, langdonholmes commented on src/plugins/auto-content/server/services/mdx-service.js
> +    content = content.trim().replace("\n\n","\n")
Why does the filter function include info, callout, etc. then? It looks like this is being applied to multiple elements. If it is just being applied (or only intended to be applied) to blockquotes, then let's make that more clear in the code.

2024-08-02 02:13 UTC, langdonholmes commented
Looks like we both solved the refreshing page issue at the same time! I also removed the "{language} Sandbox" header in the CodingSandbox element. It looks like this was added in order to retrieve the language during MDX parsing, but we can get that from the DOM (inside `<pre><code class="language-javascript">`).

I'm approving this, but I wanted to flag one additional issue.

Text is allowed inside the Accordion element, but this text is ignored at the parsing stage. 
![image](https://github.com/user-attachments/assets/6dfd621f-21c3-4b80-ac64-705b3c8af55f)

2024-08-02 02:15 UTC, langdonholmes approved these changes

2024-08-02 02:37 UTC, merged